site_name: Koki
pages:
 - Home: index.md
 - Short: short/index.md
theme: cinder
repo_url: https://github.com/koki/koki
extra_css:
   - custom/tweaks.css
site_favicon: favicon.ico
google_analytics:
   - UA-111365986-1
   - auto 
